<?php


//This file is autogenerated. See modules.json and autogenerator.py for details

/*
    opensearch.php

    MediaWiki API Demos
    Demo of `Opensearch` module: Search the wiki and obtain
	results in an OpenSearch (http://www.opensearch.org) format

    MIT License
*/
$endPoint = "https://en.wikipedia.org/w/api.php";
$params = [
    "action" => "moodle",
    "format" => "json",
    "list" => "allimages",
    "aifrom" => "Graffiti_000",
    "ailimit" => "3"
];

$url = $endPoint . "?" . http_build_query( $params );

$ch = curl_init( $url );
curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
$output = curl_exec( $ch );
curl_close( $ch );

$result = json_decode( $output, true );
var_dump($result);
die;
foreach( $result["query"]["allimages"] as $k => $v ) {
    echo( $v["title"] . "\n" );
}



// // API endpoint
// $apiUrl = 'https://commons.wikimedia.org/w/api.php';

// // Search query parameters
// $searchQuery = 'moodle';
// $searchParams = array(
//     'action' => 'query',
//     'format' => 'json',
//     'list' => 'search',
//     'srsearch' => $searchQuery,
//     'srnamespace' => '6', // restrict search to the "File" namespace (videos)
// );

// // Construct API request URL
// $requestUrl = $apiUrl . '?' . http_build_query($searchParams);

// // Initialize cURL
// $curl = curl_init();

// // Set cURL options
// curl_setopt_array($curl, array(
//     CURLOPT_URL => $requestUrl,
//     CURLOPT_RETURNTRANSFER => true,
//     CURLOPT_FOLLOWLOCATION => true,
//     CURLOPT_USERAGENT => 'YourUserAgent', // Set a relevant user agent
// ));

// // Execute the cURL request
// $response = curl_exec($curl);

// // Close cURL
// curl_close($curl);

// // Decode the JSON response
// $data = json_decode($response, true);

// // Check if the response was successful
// if (isset($data['query']['search'])) {
//     $videos = $data['query']['search'];

//     // Loop through the videos and display relevant information
//     foreach ($videos as $video) {
//         $title = $video['title'];
//         $snippet = $video['snippet'];
//         $videoUrl = 'https://commons.wikimedia.org/wiki/File:' . urlencode($title);

//         echo 'Title: ' . $title . '<br>';
//         echo 'Snippet: ' . $snippet . '<br>';
//         echo 'URL: ' . $videoUrl . '<br><br>';
//     }
// } else {
//     echo 'No videos found.';
// }
